"""
Generate precomputed forecast JSON artifacts for free-hosted deployments.

The first production use is severe composites. Those products combine several
component fields and should be generated by a scheduled job instead of inside
Render request workers.
"""

from __future__ import annotations

import argparse
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
import os
from pathlib import Path
import sys
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from forecast import artifact_cache
from forecast import aws_grib
from forecast import nomads
from routes import forecast_routes
from routes.helpers import _nan_safe


DEFAULT_VARIABLES = [
    "effective_bulk_shear",
    "stp_approx",
    "scp",
    "ship",
    "critical_angle_composite",
]

REGIONS = {
    "conus": {"lat_min": 24.0, "lat_max": 50.0, "lon_min": -125.0, "lon_max": -66.0},
}

MODEL_CONFIG = {
    "gfs": {"max_hour": 120, "step": 3},
    "hrrr": {"max_hour": 48, "step": 1},
    "nam": {"max_hour": 84, "step": 3},
    "rap": {"max_hour": 51, "step": 1},
}


def _split_csv(values: Iterable[str]) -> list[str]:
    result: list[str] = []
    for value in values:
        result.extend(part.strip() for part in value.split(",") if part.strip())
    return result


def _latest_synoptic_run(now: datetime | None = None, lag_hours: int = 2) -> str:
    current = now or datetime.now(timezone.utc)
    effective = current - timedelta(hours=lag_hours)
    cycle = (effective.hour // 6) * 6
    run_time = effective.replace(hour=cycle, minute=0, second=0, microsecond=0)
    return f"{run_time:%Y%m%d}/{cycle:02d}z"


def _valid_time(run: str, fhour: int) -> str:
    run_date, cycle_token = run.split("/")
    cycle = int(cycle_token.rstrip("z"))
    run_time = datetime.strptime(run_date, "%Y%m%d").replace(
        hour=cycle,
        tzinfo=timezone.utc,
    )
    return (run_time + timedelta(hours=int(fhour))).strftime("%Y-%m-%dT%H:%M:%SZ")


def _parse_run(run: str) -> tuple[str, int]:
    run_date, cycle_token = run.split("/")
    return run_date, int(cycle_token.rstrip("z"))


@contextmanager
def _force_source_run(run: str):
    run_date, run_cycle = _parse_run(run)
    original_nomads_find = nomads._find_latest_run
    original_nomads_iter = nomads._iter_run_candidates
    original_aws_find = aws_grib._find_latest_run
    original_aws_iter = aws_grib._iter_run_candidates

    def fixed_find(_model):
        return run_date, run_cycle

    def fixed_iter(_model, max_candidates=6):
        return [(run_date, run_cycle)]

    nomads._find_latest_run = fixed_find
    nomads._iter_run_candidates = fixed_iter
    aws_grib._find_latest_run = fixed_find
    aws_grib._iter_run_candidates = fixed_iter
    try:
        yield
    finally:
        nomads._find_latest_run = original_nomads_find
        nomads._iter_run_candidates = original_nomads_iter
        aws_grib._find_latest_run = original_aws_find
        aws_grib._iter_run_candidates = original_aws_iter


def _hours_for_model(model: str, hours_arg: str) -> list[int]:
    if hours_arg != "auto":
        values: set[int] = set()
        for part in hours_arg.split(","):
            part = part.strip()
            if not part:
                continue
            if "-" in part:
                start, end = part.split("-", 1)
                values.update(range(int(start), int(end) + 1))
            else:
                values.add(int(part))
        return sorted(values)

    config = MODEL_CONFIG[model]
    return list(range(0, config["max_hour"] + 1, config["step"]))


def _fetch_component(model: str, component: str, fhour: int, bbox: dict[str, float]):
    if component == "temperature_500hPa_raw":
        t850 = _fetch_artifact_grid(model, "temperature_850hPa", fhour, bbox)
        values = [
            [(value - 25.0 if value is not None else None) for value in row]
            for row in t850["values"]
        ]
        return {**t850, "variable": component, "values": values}

    return _fetch_artifact_grid(model, component, fhour, bbox)


def _fetch_artifact_grid(model: str, variable: str, fhour: int, bbox: dict[str, float]):
    grid = forecast_routes._fetch_grid(model, variable, fhour, bbox)
    return forecast_routes.thin_grid_result(
        grid,
        bbox=bbox,
        max_cells=forecast_routes._COMPOSITE_MAX_MAP_CELLS,
        max_side=forecast_routes._COMPOSITE_MAX_MAP_SIDE,
    )


def _build_artifact(
    model: str,
    variable: str,
    fhour: int,
    bbox: dict[str, float],
    run: str,
    generated_at: str,
):
    comp = forecast_routes.COMPOSITE_PARAMS[variable]
    grids = {
        component: _fetch_component(model, component, fhour, bbox)
        for component in comp["components"]
    }
    compute_fn = getattr(forecast_routes, comp["compute"])
    result = compute_fn(grids, fhour)
    result["run"] = run
    result["valid_time"] = _valid_time(run, fhour)
    result["artifact_generated_at"] = generated_at
    result["artifact_cycle"] = run
    result["source"] = "precomputed_artifact"
    return _nan_safe(result)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate forecast JSON artifacts.")
    parser.add_argument("--models", nargs="+", default=["hrrr"])
    parser.add_argument("--variables", nargs="+", default=DEFAULT_VARIABLES)
    parser.add_argument("--regions", nargs="+", default=["conus"])
    parser.add_argument("--hours", default="auto")
    parser.add_argument("--cycle", default=None, help="Run cycle token, e.g. 20260523/06z.")
    parser.add_argument("--artifact-dir", default=None)
    args = parser.parse_args()

    if args.artifact_dir:
        os.environ["FORECAST_ARTIFACT_DIR"] = args.artifact_dir

    models = _split_csv(args.models)
    variables = _split_csv(args.variables)
    regions = _split_csv(args.regions)
    run = args.cycle or _latest_synoptic_run()
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    total = 0
    with _force_source_run(run):
        for model in models:
            model_key = model.lower()
            if model_key not in MODEL_CONFIG:
                raise SystemExit(f"Unsupported artifact model: {model}")
            hours = _hours_for_model(model_key, args.hours)
            for region in regions:
                if region not in REGIONS:
                    raise SystemExit(f"Unsupported artifact region: {region}")
                bbox = REGIONS[region]
                for variable in variables:
                    if variable not in forecast_routes.COMPOSITE_PARAMS:
                        raise SystemExit(f"Unsupported artifact variable: {variable}")
                    for fhour in hours:
                        payload = _build_artifact(model_key, variable, fhour, bbox, run, generated_at)
                        if not artifact_cache.store_latest(model_key, variable, fhour, bbox, payload):
                            raise SystemExit(f"Failed to store {model_key}/{variable}/f{fhour:03d}")
                        total += 1
                        print(f"wrote {model_key}/{variable}/f{fhour:03d}/{region}")

    print(f"Generated {total} forecast artifacts for {run}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
